development:
  bucket: use-dev
  access_key_id: AKIAIHEPYQC4GHTWJWXQ
  secret_access_key: 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
  max_file_size: 524288000
  acl: public-read
  
test:
  bucket: use-test
  access_key_id: AKIAIHEPYQC4GHTWJWXQ
  secret_access_key: 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
  max_file_size: 524288000
  acl: public-read
  
production:
  bucket: use-production
  access_key_id: AKIAIHEPYQC4GHTWJWXQ
  secret_access_key: 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
  max_file_size: 524288000
  acl: public-read